spring.application.name=finmathly

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

spring.datasource.url=jdbc:postgresql://localhost:5432/finmathly_db
spring.datasource.username=william
spring.datasource.password=${WILLIAM_USER_DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none

spring.flyway.enabled=true
spring.flyway.url=jdbc:postgresql://localhost:5432/finmathly_db
spring.flyway.user=flyway
spring.flyway.password=${FLYWAY_USER_DB_PASSWORD}
spring.flyway.baseline-version=1