spring.datasource.url=${DEV_JDBC_DATABASE_URL}
spring.datasource.username=${DEV_JDBC_DATABASE_USERNAME}
spring.datasource.password=${DEV_JDBC_DATABASE_PASSWORD}

spring.flyway.enabled=true
spring.flyway.url=${DEV_JDBC_DATABASE_URL}
spring.flyway.user=${DEV_JDBC_FLYWAY_USERNAME}
spring.flyway.password=${DEV_JDBC_FLYWAY_PASSWORD}